#!/bin/sh

    # Change the next 3 lines to suit where you install your script and what you want to call it
    DIR=/home/pi/dev/trafficlight
    DAEMON=traffic.sh
    DAEMON_NAME=traffic

    case "$1" in
            start)
                    /home/pi/dev/trafficlight/traffic.sh > /dev/null &
                    ;;

            *)

            echo "Usage: /etc/init.d/$DEAMON_NAME {start}"
            exit 1
            ;;
    esac
    
